In [14]:
#%pip install torch torchvision

In [15]:
import torch 

x = torch.tensor([1,2,3]) #

x

tensor([1, 2, 3])

In [16]:
random_tensor = torch.rand(2,3) #random tensor, 2rows, 3columns
random_tensor

tensor([[0.0931, 0.3058, 0.9329],
        [0.3822, 0.8549, 0.9154]])

In [17]:
zeros_tensor = torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
x + ones_tensor

tensor([[2., 3., 4.],
        [2., 3., 4.]])

In [20]:
a = torch.tensor([[1.,2],[3,4]])
b = torch.tensor([[5.,6],[7,8]])
a @ b #torch.matmul(a,b)

tensor([[19., 22.],
        [43., 50.]])

In [21]:
# Sum
a.sum()

tensor(10.)

In [22]:
a.mean()

tensor(2.5000)

In [23]:
#cpu, mps and possible other frameworks
#torch.cuda.is_available()
#device = torch.device("cpu") #for ordinaru cpu and CUDA

device = torch.device("mps") #for Apple Silicon

In [24]:
#Gradients

x = torch.tensor(2.0, requires_grad=True)#mode:propagate the gradients over all computatio steps
y = x**2 + 3*x +5
#2*x +3 -> 2*2 +3=7
y.backward()
x.grad

tensor(7.)

- easy NN, one gradient descent step

In [25]:
import torch.nn as nn #Neutral networks
import torch.optim as optim #optimizer framework for gradient method

# 10 inputs, 1 output -> fully connected feed-forward neutral network
NN = nn.Linear(10,1) #W*x +b, in Tensorflow -> Dense
#MLP -> Multi-Layer perception
#in Literature/Publications: FC, FFN, FFNN, MLP

loss = nn.MSELoss() #mean squared error
#loss, cost, criteria, crit

optimizer = optim.SGD(NN.parameters(), lr = 1e-2)
#lr= learning rate, eta, alpha
#NN.parameters() ... weights and biases

input_data = torch.rand(10) #random stuff, X
output = NN(input_data) #y_pred, predictions, y_hat
y = torch.ones(1) # ground truth, target, regr,

#initial value of the loss function
loss_output = loss(y, output) #Difference between reality and expectation
print(f"Loss:{loss_output:.2} (before update)")

#two magical lines
loss_output.backward() #compute gradients
optimizer.step() #update the weights and biases

output_new = NN(input_data) #here are new weights and biases
loss_new = loss(output_new, y) #value of the loss function after one update 
print((f"Loss:{loss_new :.2} (after update)"))

Loss:0.69 (before update)
Loss:0.57 (after update)


In [26]:
y

tensor([1.])

In [27]:
output # before update

tensor([0.1676], grad_fn=<ViewBackward0>)

In [28]:
output_new

tensor([0.2481], grad_fn=<ViewBackward0>)

# Mark

In [30]:
from torchvision import datasets, transforms

transform = transforms.Compose([
    transforms.ToTensor(), #convert to tensor
])

train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)
 
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=64, shuffle=False)

100%|██████████| 26.4M/26.4M [00:02<00:00, 11.2MB/s]
100%|██████████| 29.5k/29.5k [00:00<00:00, 1.46MB/s]
100%|██████████| 4.42M/4.42M [00:00<00:00, 10.3MB/s]
100%|██████████| 5.15k/5.15k [00:00<00:00, 5.99MB/s]


In [32]:
# Model
class NN(nn.Module): #class

    def __init__(self):
        super(NN,self).__init__() #init from the superclass
        self.layer1 = nn.Linear(28*28, 64) #input layer
        self.layer2 = nn.Linear(64, 32) #hidden layer
        self.layer3= nn.Linear(32, 10)   #output layer, 10 number of product categories

    def forward(self,x):  #propagate the information
        x = x.view(-1, 28*28) #flatten 2D -> 1D
        x = torch.relu(self.layer1(x)) #activate using ReLU
        x = torch.relu(self.layer2(x))
        x = self.layer3(x) #identity activation ->logit (no need to compute gradients of softmax)
        return x





In [35]:
# Now training

model = NN()
lr = 1e-4 # learning rate
loss = nn.CrossEntropyLoss() #CE because multi-class problem
optimizer = optim.SGD(model.parameters(), lr = lr)

n_epochs = 20

for epoch in range(n_epochs):
    model.train() #train mode
    running_loss = 0.0
    for images, labels in train_loader:
        optimizer.zero_grad() #reset the gradients
        #forward 
        outputs = model(images)#calculate outputs
        curr_loss = loss(outputs, labels)
        running_loss += curr_loss
        #backwards
        curr_loss.backward() #gradients
        optimizer.step() #update weights and biases
    print(f"Epoch[{epoch + 1}/{n_epochs}], Loss: {running_loss}")

Epoch[1/20], Loss: 2155.29638671875
Epoch[2/20], Loss: 2149.0478515625
Epoch[3/20], Loss: 2143.51953125
Epoch[4/20], Loss: 2138.373046875
Epoch[5/20], Loss: 2133.2880859375
Epoch[6/20], Loss: 2128.09765625
Epoch[7/20], Loss: 2122.68994140625
Epoch[8/20], Loss: 2116.93505859375
Epoch[9/20], Loss: 2110.849609375
Epoch[10/20], Loss: 2104.296875
Epoch[11/20], Loss: 2097.338134765625
Epoch[12/20], Loss: 2089.80859375
Epoch[13/20], Loss: 2081.704345703125
Epoch[14/20], Loss: 2072.987060546875
Epoch[15/20], Loss: 2063.61474609375
Epoch[16/20], Loss: 2053.505859375
Epoch[17/20], Loss: 2042.810546875
Epoch[18/20], Loss: 2031.31787109375
Epoch[19/20], Loss: 2019.077880859375
Epoch[20/20], Loss: 2006.018798828125


In [ ]:
len(train_dataset)

60000

In [37]:
len(test_dataset)

10000

In [1]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        predicted = torch.max(outputs.data, 1)[-1]
        total += labels.size(0)
        correct += (predicted==labels).sum().item()
        
accuracy = correct/total
print(f"Accuracy: {accuracy*100:.2f}%")

NameError: name 'model' is not defined